spring.application.name=clients-message
# ===============================
# DATABASE CONFIG
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/clients_message
spring.datasource.username=clients_user
spring.datasource.password=4u52HKxRBb0z
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY MIGRATIONS
# ===============================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# ===============================
# SERVER
# ===============================

server.port=8080

# ===============================
# LOGGING
# ===============================

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG


#===========================
#JOBS
#============================

jobrunr.background-job-server.enabled=true
jobrunr.dashboard.enabled=true
jobrunr.database.type=postgres
jobrunr.database.table-prefix=jobrunr_
jobrunr.database.skip-create=false


