CREATE TABLE IF NOT EXISTS tipo_credito
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate DOUBLE PRECISION NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS tipo_documento
(
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(255),
    descripcion VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS usuarios
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento_id SMALLINT,
    activo BOOLEAN NOT NULL,
    fecha_actualizacion TIMESTAMP,
    fecha_creacion TIMESTAMP,
    email VARCHAR(255),
    nombre VARCHAR(255),
    password_hash VARCHAR(255),

    CONSTRAINT fk_usuario_tipo_documento
        FOREIGN KEY (tipo_documento_id)
        REFERENCES tipo_documento(id)
);

CREATE TABLE IF NOT EXISTS creditos
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER,
    tipo_credito_id INTEGER,
    meses INTEGER,
    valor DOUBLE PRECISION,
    activo BOOLEAN NOT NULL,
    fecha_creado TIMESTAMP,

    CONSTRAINT fk_credito_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id),

    CONSTRAINT fk_credito_tipo
        FOREIGN KEY (tipo_credito_id)
        REFERENCES tipo_credito(id)
);

CREATE TABLE IF NOT EXISTS cuotas
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credito_id INTEGER,
    numerocuota INTEGER NOT NULL,
    fecha_pago DATE,
    valor_cuota DOUBLE PRECISION NOT NULL,
    activo BOOLEAN NOT NULL,

    CONSTRAINT fk_cuota_credito
        FOREIGN KEY (credito_id)
        REFERENCES creditos(id)
);